### PR TITLE
CDATA support for XML

### PR DESCRIPTION
**Pull request by PeterMosmans**
Hi,

Please see my initial version for CDATA tag support for XML files. It adds the long option `--cdata`.
By default, nothing has changed.
Only if you specify the `--cdata` option and parse an XML file containing CDATA tags, then the CDATA tags will remain unchanged. Without the `--cdata` option, the CDATA tags are removed (which is now the default).

See #76 for the initial request.

Thanks for your consideration!

### CODE REVIEW

**Comment by ale-rt** [comment]
Thanks again, very appreciated!
I would not add the `--cdata` flag, I think that if the original xml has it we should not remove it.
zpretty should limit itself to be a formatter and not a linter.

**Comment by PeterMosmans** [comment]
Hi @ale-rt - although I agree with you that the XML file should be left untouched as much as possible, this _does_ change the current working of the formatter. Don't you think that might be an issue, backward compatibility?

**Comment by ale-rt** [comment]
For me this fixes a bug and I plan to release this in a minor release :)
I do not think anybody was using zpretty with the goal of removing CDATA from their files.

**Comment by PeterMosmans** [comment]
Do I understand it correctly that you'd like me to turn ON the feature by default, and make it optional to turn it off (e.g. `--no-cdata`) ?
There is an issue though when using this option on an XML file, and with custom DOCTYPE definitions in a document. Parts of it are incorrectly HTML-encoded.

**Comment by ale-rt** [comment]
I would not like to add any new flag, I would just like to preserve the `CDATA` by default.

**Comment by ale-rt** [comment]
@PeterMosmans would you mind to check if #79 is a valid replacement for this PR?

**Comment by ale-rt** [comment]
Superseded by #79

**Pull request closed without merging**
